##==================================================================================================
##  KUMI - Cmpact C++20 Tuple Toolbox
##  Copyright : KUMI Project Contributors
##  SPDX-License-Identifier: BSL-1.0
##==================================================================================================

##==================================================================================================
## Actual tests
##==================================================================================================
generate_test("doc/adapt.cpp"             )
generate_test("doc/all_of.cpp"            )
generate_test("doc/any_of.cpp"            )
generate_test("doc/apply.cpp"             )
generate_test("doc/as_flat_ptr.cpp"       )
generate_test("doc/as_tuple.cpp"          )
generate_test("doc/back-front.cpp"        )
generate_test("doc/cat.cpp"               )
generate_test("doc/cartesian_product.cpp" )
generate_test("doc/cast.cpp"              )
generate_test("doc/count_if.cpp"          )
generate_test("doc/count.cpp"             )
generate_test("doc/extract.cpp"           )
generate_test("doc/flatten.cpp"           )
generate_test("doc/flatten_all.cpp"       )
generate_test("doc/fold_left.cpp"         )
generate_test("doc/fold_right.cpp"        )
generate_test("doc/for_each_index.cpp"    )
generate_test("doc/for_each.cpp"          )
generate_test("doc/forward_as_tuple.cpp"  )
generate_test("doc/from_tuple.cpp"        )
generate_test("doc/generate.cpp"          )
generate_test("doc/get.cpp"               )
generate_test("doc/index.cpp"             )
generate_test("doc/inner_product.cpp"     )
generate_test("doc/iota.cpp"              )
generate_test("doc/locate.cpp"            )
generate_test("doc/make_tuple.cpp"        )
generate_test("doc/map_index.cpp"         )
generate_test("doc/map.cpp"               )
generate_test("doc/max_flat.cpp"          )
generate_test("doc/max.cpp"               )
generate_test("doc/min_flat.cpp"          )
generate_test("doc/min.cpp"               )
generate_test("doc/none_of.cpp"           )
generate_test("doc/pop_back.cpp"          )
generate_test("doc/pop_front.cpp"         )
generate_test("doc/push_back.cpp"         )
generate_test("doc/push_front.cpp"        )
generate_test("doc/reorder.cpp"           )
generate_test("doc/split.cpp"             )
generate_test("doc/subscript.cpp"         )
generate_test("doc/tie.cpp"               )
generate_test("doc/transpose.cpp"         )
generate_test("doc/to_ref.cpp"            )
generate_test("doc/to_tuple.cpp"          )
generate_test("doc/zip.cpp"               )
