var searchData=
[
  ['partition_0',['partition',['../group__kumi__generators.html#ga4643116b2dc0dfbd0d15fee408a9c18c',1,'kumi']]],
  ['plus_1',['plus',['../group__kumi__functional.html#gab83f5dbd77ab8618b7925c9de6adb54d',1,'kumi::function']]],
  ['pop_5ffront_2',['pop_front',['../group__kumi__generators.html#ga38d1ddeb5090405e79e9b7d898a85133',1,'kumi']]],
  ['pre_20requisites_3',['Pre-requisites',['../kumi_setup.html#prerequisit',1,'']]],
  ['predicate_4',['predicate',['../group__kumi__utility.html#ga9c8c29e8a2f4f5e8a663200559fdc983',1,'kumi']]],
  ['prod_5',['prod',['../group__kumi__reductions.html#ga6c139ebafaebc0f7dbca2fd57aee943c',1,'kumi']]],
  ['product_20constructions_20the_20logic_20of_20and_6',['Product Constructions (The Logic of &quot;AND&quot;)',['../kumi_product.html#product_construction',1,'']]],
  ['product_20type_2027_7',['Product Type \\( (A \\times B) \\)',['../kumi_product.html#kumi_product_type',1,'']]],
  ['product_20type_20algorithms_8',['Product Type Algorithms',['../group__kumi__algorithm.html',1,'']]],
  ['product_20type_20generalized_20reductions_9',['Product Type Generalized Reductions',['../group__kumi__reductions.html',1,'']]],
  ['product_20type_20generators_10',['Product Type Generators',['../group__kumi__generators.html',1,'']]],
  ['product_20type_20queries_11',['Product Type Queries',['../group__kumi__queries.html',1,'']]],
  ['product_20type_20related_20concepts_12',['Product Type Related Concepts',['../group__kumi__concepts.html',1,'']]],
  ['product_20type_20related_20traits_13',['Product Type Related Traits',['../group__kumi__traits.html',1,'']]],
  ['product_20type_20transformations_14',['Product Type Transformations',['../group__kumi__transforms.html',1,'']]],
  ['product_20types_15',['Product Types',['../kumi_product.html',1,'']]],
  ['product_20types_20and_20associated_20functions_16',['Product Types and associated Functions',['../group__kumi__tuple__related.html',1,'']]],
  ['product_5ftype_17',['product_type',['../conceptkumi_1_1concepts_1_1product__type.html',1,'kumi::concepts']]],
  ['programming_20languages_20considerations_18',['Programming Languages Considerations',['../kumi_product.html#tuple_programming',1,'']]],
  ['projection_19',['projection',['../conceptkumi_1_1concepts_1_1projection.html',1,'kumi::concepts']]],
  ['projection_5fmap_20',['projection_map',['../structkumi_1_1projection__map.html',1,'kumi::projection_map&lt; V &gt;'],['../conceptkumi_1_1concepts_1_1projection__map.html',1,'kumi::concepts'],['../group__kumi__utility.html#ga8b7f4e6ed1e7071d7c152c9870709fcb',1,'kumi::projection_map()']]],
  ['protocol_21',['Tuple Protocol',['../kumi_cpp_spec.html#autotoc_md128',1,'']]],
  ['public_20release_22',['First autonomous public release.',['../kumi_changelog.html#autotoc_md121',1,'']]],
  ['push_5ffront_23',['push_front',['../group__kumi__generators.html#gad4bd53f162f63af0cbfbd68d8adb5d5c',1,'kumi']]]
];
