var searchData=
[
  ['table_0',['Summary Table',['../nomenclature.html#autotoc_md163',1,'']]],
  ['terms_1',['C++ Specific Terms',['../cpp_spec.html',1,'']]],
  ['the_200_20and_201_20of_20types_2',['The Identity Elements (The &quot;0&quot; and &quot;1&quot; of Types)',['../identity.html',1,'']]],
  ['the_20c_2020_20compact_20tuple_20tools_3',['The C++20 Compact Tuple Tools',['../index.html',1,'']]],
  ['the_20curry_20howard_20correspondence_4',['The Curry-Howard Correspondence',['../introduction.html#curry_howard',1,'']]],
  ['the_20identity_20elements_20the_200_20and_201_20of_20types_5',['The Identity Elements (The &quot;0&quot; and &quot;1&quot; of Types)',['../identity.html',1,'']]],
  ['the_20logic_20of_20and_6',['Product Constructions (The Logic of &quot;AND&quot;)',['../product.html#product_construction',1,'']]],
  ['the_20source_7',['Install from the source',['../setup.html#setup-source',1,'']]],
  ['theoretic_20foundations_8',['Type Theoretic Foundations',['../introduction.html',1,'']]],
  ['tools_9',['The C++20 Compact Tuple Tools',['../index.html',1,'']]],
  ['tuple_10',['Tuple',['../index.html#autotoc_md167',1,'']]],
  ['tuple_20protocol_11',['Tuple Protocol',['../cpp_spec.html#autotoc_md141',1,'']]],
  ['tuple_20tools_12',['The C++20 Compact Tuple Tools',['../index.html',1,'']]],
  ['type_13',['type',['../cpp_spec.html#autotoc_md137',1,'Aggregate type'],['../group__utility_gab3919ec6f8098dd1fdafe9c3a79ef0dc.html#autotoc_md0',1,'Helper type'],['../group__utility_gafe5ca3b16c26d385085be7a73a1fa374.html#autotoc_md2',1,'Helper type'],['../group__utility_gabf2013046cf8ec8ac781128a815709cc.html#autotoc_md4',1,'Helper type'],['../group__utility_gafc8e80ba53336a0142f3267959c1ba71.html#autotoc_md6',1,'Helper type'],['../group__utility_ga59477c1d8542af2601f493e3320434ee.html#autotoc_md8',1,'Helper type'],['../structkumi_1_1function_1_1element__or.html#autotoc_md22',1,'Helper type'],['../structkumi_1_1as__tuple.html#autotoc_md48',1,'Helper type'],['../structkumi_1_1common__product__type.html#autotoc_md62',1,'Helper type'],['../structkumi_1_1element.html#autotoc_md86',1,'Helper type'],['../structkumi_1_1member.html#autotoc_md87',1,'Helper type'],['../structkumi_1_1container__type.html#autotoc_md91',1,'Helper type'],['../structkumi_1_1stored__member.html#autotoc_md95',1,'Helper type'],['../structkumi_1_1stored__element.html#autotoc_md96',1,'Helper type'],['../structkumi_1_1all__uniques.html#autotoc_md97',1,'Helper type'],['../structkumi_1_1all__unique__names.html#autotoc_md99',1,'Helper type'],['../structkumi_1_1is__equivalent.html#autotoc_md101',1,'Helper type'],['../structkumi_1_1is__equality__comparable.html#autotoc_md103',1,'Helper type'],['../structkumi_1_1apply__traits.html#autotoc_md105',1,'Helper type'],['../structkumi_1_1map__traits.html#autotoc_md107',1,'Helper type'],['../cpp_spec.html#autotoc_md139',1,'Structural type']]],
  ['type_2027_14',['Product Type \\( (A \\times B) \\)',['../product.html#product_type',1,'']]],
  ['type_2038_15',['Record Type \\( (\\{l_A: A\\} \\times \\{l_B: B\\}) \\)',['../product.html#record_type',1,'']]],
  ['type_20_3a_200_16',['Empty Type : \\( (0 / \\bot) \\)',['../identity.html#empty',1,'']]],
  ['type_20_3a_203_17',['Unit Type : \\( (1 / \\top) \\)',['../identity.html#unit',1,'']]],
  ['type_20cardinality_18',['Type Cardinality',['../introduction.html#cardinality',1,'']]],
  ['type_20theoretic_20foundations_19',['Type Theoretic Foundations',['../introduction.html',1,'']]],
  ['types_20',['Types',['../product.html',1,'Product Types'],['../identity.html',1,'The Identity Elements (The &quot;0&quot; and &quot;1&quot; of Types)']]],
  ['types_20_3a_21',['Example types :',['../conceptkumi_1_1concepts_1_1projection__map.html#autotoc_md72',1,'']]],
  ['types_3a_22',['types:',['../conceptkumi_1_1concepts_1_1product__type.html#autotoc_md65',1,'Example types:'],['../conceptkumi_1_1concepts_1_1record__type.html#autotoc_md66',1,'Example types:'],['../conceptkumi_1_1concepts_1_1container.html#autotoc_md67',1,'Example types:'],['../conceptkumi_1_1concepts_1_1static__container.html#autotoc_md68',1,'Example types:'],['../conceptkumi_1_1concepts_1_1index.html#autotoc_md69',1,'Example types:'],['../conceptkumi_1_1concepts_1_1field.html#autotoc_md70',1,'Example types:'],['../conceptkumi_1_1concepts_1_1identifier.html#autotoc_md71',1,'Example types:'],['../conceptkumi_1_1concepts_1_1homogeneous__product__type.html#autotoc_md73',1,'Example types:']]]
];
