##======================================================================================================================
##  KUMI - Compact C++20 Tuple Toolbox
##  Copyright : KUMI Project Contributors
##  SPDX-License-Identifier: BSL-1.0
##======================================================================================================================
name: Unit Tests
on:
  pull_request:
    branches:
      - main
concurrency:
  group: kumi-unit-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ##======================================================================================================================
  ## Preserve pre-commit checks
  ##======================================================================================================================
  precommit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.x'
      - name: Install pre-commit
        run: pip install pre-commit
      - name: Run pre-commit checks
        run: pre-commit run --all-files --show-diff-on-failure --color=always

  ##======================================================================================================================
  ## Build and run unit tests
  ##======================================================================================================================
  #linux-tests:
  #  name: Linux
  #  needs: precommit
  #  uses: ./.github/workflows/unit-linux.yml

  #windows-tests:
  #  name: Windows
  #  needs: precommit
  #  uses: ./.github/workflows/unit-windows.yml

  #macos-tests:
  #  name: MacOS
  #  needs: precommit
  #  uses: ./.github/workflows/unit-macos.yml

  nvidia-tests:
    name: Nvidia
    needs: precommit
    uses: ./.github/workflows/nvidia.yml
