##======================================================================================================================
##  KUMI - Compact C++20 Tuple Toolbox
##  Copyright : KUMI Project Contributors
##  SPDX-License-Identifier: BSL-1.0
##======================================================================================================================
name: KUMI Integration Tests
on:
  push:
    branches:
      - main

concurrency:
  group: kumi-integration-${{ github.ref }}
  cancel-in-progress: true

jobs:
  integration:
    uses: jfalcou/copacabana/.github/workflows/integration.yml@05d0796125e284daa16d9a4f6424c58f98a2bb5a # v7
    with:
      project: kumi
      cxx-compiler: clang++
