##======================================================================================================================
##  KUMI - Compact C++20 Tuple Toolbox
##  Copyright : KUMI Project Contributors
##  SPDX-License-Identifier: BSL-1.0
##======================================================================================================================
name: KUMI Integration Tests
on:
  push:
    branches:
      - main

concurrency:
  group: kumi-integration-${{ github.ref }}
  cancel-in-progress: true

jobs:
  integration:
    uses: jfalcou/copacabana/.github/workflows/integration.yml@17df3f26736d3a0ecc231a3b951f548dcbc09c45 # v2
    with:
      project: kumi
      cxx-compiler: clang++
