##======================================================================================================================
##  KUMI - Compact C++20 Tuple Toolbox
##  Copyright : KUMI Project Contributors
##  SPDX-License-Identifier: BSL-1.0
##======================================================================================================================
name: KUMI CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  gcc-linux:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/jfalcou/compilers:v7
    strategy:
      fail-fast: false
      matrix:
        cfg:
        - { opts: -O0                 }
        - { opts: "-O3 -flto -DNDEBUG"}
    steps:
      - name: Fetch current branch
        uses: actions/checkout@v3
      - name: KUMI using g++-11 with ${{ matrix.cfg.opts }}
        run:  |
          mkdir build
          cd build
          cmake ..  -G Ninja -DCMAKE_CXX_COMPILER=g++-11 -DCMAKE_CXX_FLAGS="${{ matrix.cfg.opts }}"
      - name: Compile Unit Tests
        run:  |
          cd build
          ninja kumi-test -j 2
      - name: Running Unit Tests
        run:  |
          cd build
          ctest --output-on-failure -j 2

  gcc12-linux:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/jfalcou/compilers:v7
    strategy:
      fail-fast: false
      matrix:
        cfg:
        - { opts: -O0                 }
        - { opts: "-O3 -flto -DNDEBUG"}
    steps:
      - name: Fetch current branch
        uses: actions/checkout@v3
      - name: KUMI using g++-12 with ${{ matrix.cfg.opts }}
        run:  |
          mkdir build
          cd build
          cmake ..  -G Ninja -DCMAKE_CXX_COMPILER=g++ -DCMAKE_CXX_FLAGS="${{ matrix.cfg.opts }}"
      - name: Compile Unit Tests
        run:  |
          cd build
          ninja kumi-test -j 2
      - name: Running Unit Tests
        run:  |
          cd build
          ctest --output-on-failure -j 2

  clang-linux:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/jfalcou/compilers:v7
    strategy:
      fail-fast: false
      matrix:
        cfg:
        - { opts: -O0                                 , linker:                }
        - { opts: "-O3 -flto -DNDEBUG"                , linker:                }
        - { opts: "-O3 -flto -DNDEBUG -stdlib=libc++" , linker: -stdlib=libc++ }
        - { opts: "-O0 -stdlib=libc++"                , linker: -stdlib=libc++ }
    steps:
      - name: Fetch current branch
        uses: actions/checkout@v3
      - name: KUMI using clang++ with ${{ matrix.cfg.opts }}
        run:  |
          mkdir build
          cd build
          cmake ..  -G Ninja  -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_CXX_FLAGS="${{ matrix.cfg.opts }}" \
                              -DCMAKE_EXE_LINKER_FLAGS="${{ matrix.cfg.linker }}"
      - name: Compile Unit Tests
        run:  |
          cd build
          ninja kumi-test -j 2
      - name: Running Unit Tests
        run:  |
          cd build
          ctest --output-on-failure -j 2

  clang-macosx:
    runs-on: [macos-12]
    strategy:
      fail-fast: false
      matrix:
        cfg:
        - { opts: -O0                                 , linker:                 }
        - { opts: "-O0 -stdlib=libc++"                , linker: -stdlib=libc++  }
        - { opts: "-O3 -flto -DNDEBUG"                , linker:                 }
        - { opts: "-O3 -flto -DNDEBUG -stdlib=libc++" , linker: -stdlib=libc++  }
    steps:
      - name: Fetch current branch
        uses: actions/checkout@v3
      - name: Running CMake for clang++ with ${{ matrix.cfg.opts }}
        run: |
          mkdir build && cd build
          cmake .. -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_CXX_FLAGS="${{ matrix.cfg.opts }}" -DCMAKE_EXE_LINKER_FLAGS="${{ matrix.cfg.linker }}"
      - name: Compiling Unit Tests
        run:  cd build && make kumi-test -j 2
      - name: Running Unit Tests
        run: cd build && ctest --output-on-failure -j 2

  gcc-macosx:
    runs-on: [macos-11]
    strategy:
      fail-fast: false
      matrix:
        cfg:
        - { opts: -O0                 }
        - { opts: "-O3 -flto -DNDEBUG"}
    steps:
      - name: Fetch current branch
        uses: actions/checkout@v3
      - name: Running CMake for g++-11 with ${{ matrix.cfg.opts }}
        run: |
          mkdir build && cd build
          cmake .. -DCMAKE_CXX_COMPILER=g++-11 -DCMAKE_CXX_FLAGS="${{ matrix.cfg.opts }}"
      - name: Compiling Unit Tests
        run:  cd build && make kumi-test -j 2
      - name: Running Unit Tests
        run: cd build && ctest --output-on-failure -j 2

  android:
    runs-on: [macos-12]
    strategy:
      fail-fast: false
      matrix:
        cfg:
        - { opts: -O0                 }
        - { opts: "-O3 -flto -DNDEBUG"}
    steps:
      - name: Fetch current branch
        uses: actions/checkout@v3
      - name: Running CMake for g++ with ${{ matrix.cfg.opts }}
        run: |
          mkdir build && cd build
          cmake .. -DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK_ROOT/build/cmake/android.toolchain.cmake -DANDROID_ABI=arm64-v8a
      - name: Compiling Unit Tests
        run:  cd build && make kumi-test -j 2

  msvc:
    runs-on: [windows-2022]
    strategy:
      fail-fast: false
      matrix:
        cfg:
        - { mode: Debug  , options: ""}
        - { mode: Release, options: ""}
    steps:
      - name: Fetch current branch
        uses: actions/checkout@v3
      - name: Running CMake for MSVC ${{ matrix.cfg.mode }} ${{ matrix.cfg.options }}
        run: |
          mkdir build && cd build
          cmake -G "Visual Studio 17 2022" -A x64 .. -DKUMI_BUILD_TEST=ON
      - name: Compiling Unit Tests
        run:  |
          cd build
          cmake --build . --target kumi-test --config ${{ matrix.cfg.mode }} --parallel 2
      - name: Running Tests
        run: |
          cd build
          ctest -C ${{ matrix.cfg.mode }} --output-on-failure

  clang-cl:
    runs-on: [windows-2022]
    strategy:
      fail-fast: false
      matrix:
        cfg:
        - { mode: Debug  , options: ""}
        - { mode: Release, options: ""}
    steps:
      - name: Fetch current branch
        uses: actions/checkout@v3
      - name: Running CMake for Clang-CL ${{ matrix.cfg.mode }} ${{ matrix.cfg.options }}
        run: |
          mkdir build && cd build
          cmake -G "Visual Studio 17 2022" -T ClangCL -A x64 .. -DKUMI_BUILD_TEST=ON
      - name: Compiling Unit Tests
        run:  |
          cd build
          cmake --build . --target kumi-test --config ${{ matrix.cfg.mode }} --parallel 2
      - name: Running Tests
        run: |
          cd build
          ctest -C ${{ matrix.cfg.mode }} --output-on-failure

  wasm:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/jfalcou/compilers:v7
    strategy:
      fail-fast: false
      matrix:
        cfg:
        - { opts: -O0                 }
        - { opts: "-O3 -flto -DNDEBUG"}
    steps:
      - name: Fetch current branch
        uses: actions/checkout@v3
      - name: KUMI using em++ with ${{ matrix.cfg.opts }}
        run:  |
          mkdir build
          cd build
          emcmake cmake ..  -G Ninja -DCMAKE_CXX_COMPILER=em++ -DCMAKE_CXX_FLAGS="${{ matrix.cfg.opts }}" -DCMAKE_CROSSCOMPILING_CMD="`pwd`/../cmake/run_wasm.sh"
      - name: Compile Unit Tests
        run:  |
          cd build
          ninja kumi-test -j 2
      - name: Running Unit Tests
        run:  |
          cd build
          ctest --output-on-failure -j 2
