##==================================================================================================
##  KUMI - Compact C++20 Tuple Toolbox
##  Copyright : KUMI Project Contributors
##  SPDX-License-Identifier: BSL-1.0
##==================================================================================================
name: KUMI Linux Tests
on:
  workflow_call:

jobs:
  linux:
    name: ${{ matrix.compiler.name }}
    runs-on: self-hosted
    strategy:
      fail-fast: false
      matrix:
        compiler:
          - &nvcc {
              name: "Cuda C++",
              bin: "nvcc",
            }
          #- &clang {
          #    name: "clang++",
          #    bin: "clang++",
          #    flags: "--cuda-gpu-arch=sm_75 -lcudart_static -L/opt/cuda/lib64/ -ldl -lrt -pthread"
          #  }
    steps:
      - name:  Fetch current branch
        uses: actions/checkout@v4.1.1

      - name: Configure CMake
        run: |
          cmake -S . -B build -G Ninja                      \
          -DCMAKE_CUDA_COMPILER=${{ matrix.compiler.bin }}   \
          -DCMAKE_CXX_FLAGS="${{ matrix.compiler.flags }}"

      - name: Compile Unit Tests
        run: cd build && ninja device.cu -j 2

      - name: Run Tests
        run: cd build && ctest -R ^device.cu --output-on-failure -j 2
