##==================================================================================================
##  KUMI - Compact C++20 Tuple Toolbox
##  Copyright : KUMI Project Contributors
##  SPDX-License-Identifier: BSL-1.0
##==================================================================================================
name: KUMI Windows Tests
on:
  workflow_call:

jobs:
  windows:
    name: ${{ matrix.compiler.name }} (${{ matrix.options }})
    runs-on: windows-2022
    strategy:
      fail-fast: false
      matrix:
        compiler:
          - &msvc     { name: "MSVC"    , flags: ""           }
          - &clangcl  { name: "Clang-CL", flags: "-T ClangCL" }
        options: [Debug, Release]
    steps:
      - name: Fetch current branch
        uses: actions/checkout@v4.1.1

      - name: Configure CMake
        run: cmake -S . -B build -G "Visual Studio 17 2022" -A x64 ${{ matrix.compiler.flags }}

      - name: Compile Unit Tests
        run: cmake --build build --target kumi-test --config ${{ matrix.options }} --parallel 2

      - name: Run Tests
        run: cd build && ctest -C ${{ matrix.options }} --output-on-failure
